### ISSUE TITLE
[0.0pt] GROUP MEMBERS[2]

### ISSUE THREAD

**Issue by citec-47** [adeola003/Javascript_Capstone_project#21]
### **#MEMBERS**
*Project link*: https://github.com/adeola003/Javascript_Capstone_project/projects?type=classic

- Abdel-Khafid kolawole Fifa SALAOU
- Ndonyi Maurice Djam

**Comment by wayungi** [comment]
Hi @citec-47  & @adeola003 , 

![image](https://user-images.githubusercontent.com/99656687/224543672-ce29b4b2-d478-447f-ae6f-eb3df4f35902.png)

**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] Good work setting the kanban board ✔️ 
- [ ] Tasks for student C have been removed ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] You have not assigned the tasks to group members. It is hard to tell which student is A or B. This is a project requirement. kindly fix this. 
![inst](https://user-images.githubusercontent.com/99656687/232438637-961c23b7-a4d8-416d-94aa-28f5d990d001.png)

- [ ] Once you have assigned the tasks, each team members icon or avater will appear in the areas where the arrows are pointing
![view](https://user-images.githubusercontent.com/99656687/232439245-ab3715d0-2a0d-4103-9a25-c00c95d6eb7a.png)

- [ ]  All cards with group tasks in the title should be assigned to someone


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @citec-47 and @adeola003,

✔️ Tasks are complete

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
